apiVersion: v1
kind: ConfigMap
metadata:
  name: matchmaking-worker-config
data:
  RabbitMQ__Host: "rabbitmq"
  RabbitMQ__Port: "5672"
  RabbitMQ__UserName: "guest"
  RabbitMQ__Password: "guest"
  RabbitMQ__QueueName: "match-making"
  Kubernetes__ServerUrl: "https://kubernetes.default.svc"
  Kubernetes__Token: ""
